### ISSUE TITLE
Clicking on notification bubble only opens qbittorrent, regardless of the notification

### ISSUE THREAD

**Issue by ghost** [AyatanaIndicators/ayatana-indicator-notifications#28] opened 2022-08-15 18:16 UTC
**Describe the bug**
If qbittorrent is running and minimized, clicking on the notification bubble for any notification maximizes qbittorrent, even if there are no qbittorrent notifications at all.

**To Reproduce**
1. Open qbittorrent and minimize the window to dock or systray
2. Clear all notifications (not essential, it will maximize qbittorrent anyway)
3. Wait for any notification bubble to appear
4. Click on the notification bubble
5. See bug - qbittorrent will maximize

**System Info**
OS: Ubuntu MATE Release 22.04.1 LTS (Jammy Jellyfish) 64-bit
Kernel: Linux 5.15.0-46-generic x86_64
DE: MATE 1.26.0

**Comment by tari01** [comment] 2023-09-07 10:13
@ghost:

I have tested this following your instructions, but I cannot reproduce it. Furthermore, the Ayatana Notifications Indicator has nothing to do with notification bubbles. It only reads the notifications via D-Bus and shows them in the menu.

Your issue is either specific to your system, or if there is a bug, it is most likely coming from libnotify or qbittorrent.

I am closing this as invalid.

**Closed by tari01** 2023-09-07 10:13 UTC
